### ISSUE TITLE
输入文本中包括#，就会报错

### ISSUE THREAD

**Issue by bigbrother666sh** [Shawn-Inspur/Yuan-1.0#13]
实测，输入其他，甚至不输入都不会报错，唯独#这个符号不行。
{'flag': False, 'errCode': 'IBASE_CONTROLLER_UNKNOWN_EXCEPTION', 'errMessage': 'ibase 未知异常', 'exceptionMsg': "Required String parameter 'type' is not present", 'resData': None}
```
(base) zeming@zemingdeMacBook-Pro yuan_api % python dialog.py
====浪潮源1.0demo====
输入Q退出
问：!
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '138e4f0887724bc3908fa57beb06d278'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '!。问：!。答：!。问：!。答：!。问：!。答：!。问：!。答：!。问：!。答：!。问：!。答：!。问：!。答：!。问：!。答：!。问：!。答：!。问：!。答：!。问：!。答：!。问：!。答：!。问：'}
答：!
输入Q退出
问：@
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': 'd77f9f847baa4770b7fdbd21b08e93cb'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '@，。问：@。答：@，。问：@。答：@。▃问：@。答：@，。问：@。答：@，。问：@。答：@，。问：@。答：@，。问：@。答：@，。▃问：@。答：@，。问：@。答：@，。问：@。答：@，。问：@。答：'}
答：@，
输入Q退出
问：$
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': 'f9a2b25f37084363823356fec3bb5f82'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '$。▃问：$。答：$。▃问：$。答：$。▃问：$。答：$。▃问：$。答：$。▃问：$。答：$。▃问：$。答：$。▃问：$。答：$。▃问：$。答：$。▃问：$。答：$。▃问：$。答：$。▃问：$。答：$'}
答：$
输入Q退出
问：%
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': 'e124f50800bf4fbead8e7a6104330f5a'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '%。▃问：%。答：%。▃问：%。答：%。▃问：%。答：%。▃问：%。答：%。▃问：%。答：%。▃问：%。答：%。▃问：%。答：%。▃问：%。答：%。▃问：%。答：%。▃问：%。答：%。▃问：%。答：%'}
答：%
输入Q退出
问：^
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '1af8cc210c7c47eb997856a94399a720'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '^。问：^。答：^。问：^。答：^。问：^。答：^。问：^。答：^。问：^。答：^。问：^。答：^。问：^。答：^。问：^。答：^。问：^。答：^。问：^。答：^。问：^。答：^。问：^。答：^。问：'}
答：^
输入Q退出
问：&
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '14da653849564cf58212d7337639ff4b'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '“你为什么要这么做？”▃他的回答很简单，“为了让你爱我。”▃我的回答也很简单，“我不爱你。”▃“我知道，你爱的人是我的哥哥。”他笑了，笑得很苦涩，“可是，他已经不在了。”▃我的心一颤，“他……他怎么了？”▃“他……”他'}
答：“你为什么要这么做？”▃他的回答很简单，“为了让你爱我
输入Q退出
问：*
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': 'ab824400c63e443e92f4396118d893af'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '*。▃问：*。答：*。▃问：*。答：*。▃问：*。答：*。▃问：*。答：*。▃问：*。答：*。▃问：*。答：*。▃问：*。答：*。▃问：*。答：*。▃问：*。答：*。▃问：*。答：*。▃问：*。答：*'}
答：*
输入Q退出
问：（
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '4704091f16294a428904d695f43d7dc8'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '（）。）。）。▃4、（。）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）。（）'}
答：（）
输入Q退出
问：-
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '1275f0f25a944136a030953e044a9f43'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '-。▃问：-。答：-。▃问：-。答：-。▃问：-。答：-。▃问：-。答：-。▃问：-。答：-。▃问：-。答：-。▃问：-。答：-。▃问：-。答：-。▃问：-。答：-。▃问：-。答：-。▃问：-。答：-'}
答：-
输入Q退出
问：+
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '8acb9e0f9c9049bd864877ebf84e652e'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '。▃问：。答：。▃问：。答：。▃问：。答：。▃问：。答：。▃问：。答：。▃问：。答：。▃问：。答：。▃问：。答：。▃问：。答：。▃问：。答：。▃问：。答：。▃问：。答：。▃问：。答：。▃问：。答：。▃'}
答：
输入Q退出
问：——
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '3a66fddb9db04cae816cbbc4fc9d078b'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '▃“你的名字叫什么？”▃“我的名字叫做‘我’。”▃“你的名字叫做‘我’。”▃“你的名字叫做‘我’。”▃“你的名字叫做‘我’。”▃“你的名字叫做‘我’。”▃“你的名字叫做‘我’。”▃“你的名字叫做‘我’。'}
答：▃“你的名字叫什么？”▃“我的名字叫做‘我’
输入Q退出
问：=
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': 'e6b145b805834d198ded69b2808e8f77'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '=，问：=。答：=。问：=。答：=。问：=。答：=。问：=。答：=。问：=。答：=。问：=。答：=。问：=。答：=。问：=。答：=。问：=。答：=。问：=。答：=。问：=。答：=。问：=。答：=。问：'}
答：=，问：=
输入Q退出
问：_
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '7d96613e7ce442a39504ea5aa102cc3a'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '_。问：_。答：_。问：_。答：_。问：_。答：_。问：_。答：_。问：_。答：_。问：_。答：_。问：_。答：_。问：_。答：_。问：_。答：_。问：_。答：_。问：_。答：_。问：_。答：_。问：'}
答：_
输入Q退出
问：\
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '76f5b92e7e184be693c67c883a369a20'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '请求异常，请重试'}
答：请求异常，请重试
输入Q退出
问：、
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '766c9a9f355943d1a94b9f7ca3677740'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '、。▃3.你对自己的学习成绩是否满意？、、。▃4.你认为你在学校里的表现怎样？、、。▃5.你认为你在班里的表现怎样？、、。▃6.你认为你在学校里的学习态度怎样？、、。▃7.你认为你在班里的学习态度怎样？、、。▃8.你认为你在学校里的学习成绩'}
答：、
输入Q退出
问：|
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': 'a6f378ba30364bb38eaf36dfd3257c35'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '|。▃“这次我们要做的是，在一个相对封闭的空间内，把我们的技术能力、运营能力和资本的力量，发挥到极致。”▃据了解，在今年的“双十一”期间，京东商城的销售额将达到300亿元，而苏宁易购也将在“双十一”期间推出“超级零元购”等活动，销售额将超过100亿元。▃在中国'}
答：|
输入Q退出
问：】
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '7c9447ca19cf49758d96092f03280b7e'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '】。▃【问：】。答：】。▃【问：】。答：】。▃【问：】。答：】。▃【问：】。答：】。▃【问：】。答：】。▃【问：】。答：】。▃【问：】。答：】。▃【问：】。答：】。▃【问：】。答：】。▃【问：】。答：'}
答：】
输入Q退出
问：/
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': 'f218747bf05f49309f1d11004665aeac'}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': None}
{'flag': True, 'errCode': None, 'errMessage': None, 'exceptionMsg': None, 'resData': '/。▃在这个过程中，我发现自己在这个过程中的一个重要的收获是，我开始学会用一种非常积极的方式来思考，而不是用一种消极的方式来思考。▃这种积极的思考，让我的心态发生了很大的变化。▃我发现，当你用一种积极的心态去看问题的时候，你会发现，这个世界其实是非常美好的，'}
答：/
输入Q退出
问：#
{'flag': False, 'errCode': 'IBASE_CONTROLLER_UNKNOWN_EXCEPTION', 'errMessage': 'ibase 未知异常', 'exceptionMsg': "Required String parameter 'type' is not present", 'resData': None}
Traceback (most recent call last):
  File "dialog.py", line 30, in <module>
    response = yuan.submit_API(prompt=prompt,trun="。")
  File "/Users/zeming/Yuan-1.0/yuan_api/inspurai.py", line 142, in submit_API
    res = self.response(query,engine=self.engine,
  File "/Users/zeming/Yuan-1.0/yuan_api/inspurai.py", line 133, in response
    raise e
  File "/Users/zeming/Yuan-1.0/yuan_api/inspurai.py", line 130, in response
    requestId = submit_request(query,temperature,topP,topK,max_tokens)
  File "/Users/zeming/Yuan-1.0/yuan_api/url_config.py", line 50, in submit_request
    raise  RuntimeWarning(response_text)
RuntimeWarning: {'flag': False, 'errCode': 'IBASE_CONTROLLER_UNKNOWN_EXCEPTION', 'errMessage': 'ibase 未知异常', 'exceptionMsg': "Required String parameter 'type' is not present", 'resData': None}
```

**Comment by lifengss** [comment]
测试了一下，输入给模型的数据是通过request的方式放在url地址里传给后台的，url地址里不能包含#（#为url网页锚点标识符，用于实现页面内跳转的），否则会报错。可以将’#‘转义为其他字符，如PostMan会把’#‘转义为’%23‘。
另外，如果输入'&'提交请求不会报错，但是会传入一个空的键值对，导致查询生成结果时对url的json解析出现问题。如确实需要使用，建议转义为’%26‘。
这个bug我们后续更新推理代码时会进行更新。感谢您的关注和宝贵意见！
